name: phoenics
channels:
  - defaults
dependencies:
  - _nb_ext_conf=0.4.0=py36_1
  - anaconda-client=1.6.6=py36h59e3ba0_0
  - asn1crypto=0.24.0=py36_0
  - binutils_impl_linux-64=2.28.1=h04c84fa_2
  - binutils_linux-64=7.2.0=25
  - bleach=1.5.0=py36_0
  - ca-certificates=2018.03.07=0
  - certifi=2018.1.18=py36_0
  - cffi=1.11.4=py36h9745a5d_0
  - chardet=3.0.4=py36h0f667ec_1
  - clyent=1.2.2=py36h7e57e65_1
  - cryptography=2.1.4=py36hd09be54_0
  - cudatoolkit=8.0=3
  - cudnn=7.0.5=cuda8.0_0
  - cycler=0.10.0=py36h93f1223_0
  - dbus=1.10.22=h3b5a359_0
  - decorator=4.2.1=py36_0
  - entrypoints=0.2.3=py36h1aec115_2
  - expat=2.2.5=he0dffb1_0
  - fontconfig=2.12.4=h88586e7_1
  - freetype=2.8=hab7d2ae_1
  - gcc_impl_linux-64=7.2.0=hc5ce805_2
  - gcc_linux-64=7.2.0=25
  - glib=2.53.6=h5d9569c_2
  - gmp=6.1.2=h6c8ec71_1
  - gst-plugins-base=1.12.2=he3457e5_0
  - gstreamer=1.12.2=h4f93127_0
  - gxx_impl_linux-64=7.2.0=hd3faf3d_2
  - gxx_linux-64=7.2.0=25
  - h5py=2.7.1=py36h3585f63_0
  - hdf5=1.10.1=h9caa474_1
  - html5lib=0.9999999=py36_0
  - icu=58.2=h9c2bf20_1
  - idna=2.6=py36h82fb2a8_1
  - intel-openmp=2018.0.0=hc7b2577_8
  - ipykernel=4.7.0=py36h2f9c1c0_0
  - ipython=6.2.1=py36h88c514a_1
  - ipython_genutils=0.2.0=py36hb52b0d5_0
  - ipywidgets=7.1.0=py36_0
  - jedi=0.11.1=py36_0
  - jinja2=2.10=py36ha16c418_0
  - joblib=0.11=py36_0
  - jpeg=9b=h024ee3a_2
  - jsonschema=2.6.0=py36h006f8b5_0
  - jupyter_client=5.2.1=py36_0
  - jupyter_core=4.4.0=py36h7c827e3_0
  - libedit=3.1=heed3624_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=7.2.0=h7cc24e2_2
  - libgfortran=3.0.0=1
  - libgfortran-ng=7.2.0=h9f7466a_2
  - libgpuarray=0.7.5=h14c3975_0
  - libpng=1.6.32=hbd3595f_4
  - libprotobuf=3.4.1=h5b8497f_0
  - libsodium=1.0.15=hf101ebd_0
  - libstdcxx-ng=7.2.0=h7a57d05_2
  - libxcb=1.12=hcd93eb1_4
  - libxml2=2.9.4=h2e8b1d7_6
  - mako=1.0.7=py36h0727276_0
  - markdown=2.6.9=py36_0
  - markupsafe=1.0=py36hd9260cd_1
  - matplotlib=2.1.1=py36ha26af80_0
  - mistune=0.8.3=py36_0
  - mkl=2017.0.4=h4c4d0af_0
  - mkl-service=1.1.2=py36_3
  - nb_anacondacloud=1.4.0=py36_0
  - nb_conda=2.2.1=py36h8118bb2_0
  - nb_conda_kernels=2.1.0=py36_0
  - nbconvert=5.3.1=py36hb41ffb7_0
  - nbformat=4.4.0=py36h31c9010_0
  - nbpresent=3.0.2=py36h5f95a39_1
  - ncurses=6.0=h9df7e31_2
  - nose=1.3.7=py36hcdf7029_2
  - notebook=5.3.1=py36_0
  - numpy=1.13.1=py36_0
  - openssl=1.0.2o=h20670df_0
  - pandas=0.22.0=py36hf484d3e_0
  - pandoc=1.19.2.1=hea2e7c5_1
  - pandocfilters=1.4.2=py36ha6701b7_1
  - parso=0.1.1=py36h35f843b_0
  - patsy=0.4.1=py36ha3be15e_0
  - pcre=8.41=hc27e229_1
  - pexpect=4.3.1=py36_0
  - pickleshare=0.7.4=py36h63277f8_0
  - pip=9.0.1=py36h6c6f9ce_4
  - prompt_toolkit=1.0.15=py36h17d85b1_0
  - protobuf=3.4.1=py36h306e679_0
  - ptyprocess=0.5.2=py36h69acd42_0
  - pycparser=2.18=py36hf9f622e_1
  - pygments=2.2.0=py36h0d3125c_0
  - pygpu=0.7.5=py36h14c3975_0
  - pymc3=3.2=py36h89408ba_0
  - pyopenssl=17.5.0=py36h20ba746_0
  - pyparsing=2.2.0=py36hee85983_1
  - pyqt=5.6.0=py36h0386399_5
  - pysocks=1.6.7=py36hd97a5b1_1
  - python=3.6.4=hc3d631a_0
  - python-dateutil=2.6.1=py36h88d3b88_1
  - pytz=2017.3=py36h63b9c63_0
  - pyyaml=3.12=py36hafb9ca4_1
  - pyzmq=16.0.3=py36he2533c7_0
  - qt=5.6.2=h974d657_12
  - readline=7.0=ha6073c6_4
  - requests=2.18.4=py36he2e5f8d_1
  - scikit-learn=0.19.0=np113py36_0
  - scipy=0.19.1=np113py36_0
  - seaborn=0.8.1=py36hfad7ec4_0
  - send2trash=1.4.2=py36_0
  - setuptools=36.5.0=py36he42e2e1_0
  - simplegeneric=0.8.1=py36h2cb9092_0
  - sip=4.18.1=py36h51ed4ed_2
  - six=1.11.0=py36h372c433_1
  - sqlite=3.20.1=hb898158_2
  - statsmodels=0.8.0=py36h8533d0b_0
  - tensorflow-gpu=1.4.1=0
  - tensorflow-gpu-base=1.4.1=py36h01caf0a_0
  - tensorflow-tensorboard=0.1.5=py36_0
  - terminado=0.8.1=py36_0
  - testpath=0.3.1=py36h8cadb63_0
  - theano=1.0.1=py36h6bb024c_0
  - tk=8.6.7=hc745277_3
  - tornado=4.5.2=py36h1283b2a_0
  - tqdm=4.19.4=py36ha5a5176_0
  - traitlets=4.3.2=py36h674d592_0
  - urllib3=1.22=py36hbe7ace6_0
  - wcwidth=0.1.7=py36hdf4376a_0
  - webencodings=0.5.1=py36h800622e_1
  - werkzeug=0.14.1=py36_0
  - wheel=0.30.0=py36hfd4bba0_1
  - widgetsnbextension=3.1.0=py36_0
  - xz=5.2.3=h55aa19d_2
  - yaml=0.1.7=had09818_2
  - zeromq=4.2.2=hbedb6e5_2
  - zlib=1.2.11=ha838bed_2
  - pip:
    - cma==2.5.3
    - cython==0.27.3
    - edward==1.3.5
    - tensorflow==1.4.1
prefix: /home/flo/anaconda3/envs/phoenics

